# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Infisical backend systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ infisical_identifier }}-backend.service"
  register: infisical_backend_service_stat

- name: Uninstall Infisical backend systemd services and files
  when: infisical_backend_service_stat.stat.exists | bool
  block:
    - name: Ensure Infisical backend systemd service is stopped
      ansible.builtin.service:
        name: "{{ infisical_identifier }}-backend"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Infisical backend systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ infisical_identifier }}-backend.service"
        state: absent

- name: Check existence of Infisical frontend systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ infisical_identifier }}-frontend.service"
  register: infisical_frontend_service_stat

- name: Uninstall Infisical frontend systemd services and files
  when: infisical_frontend_service_stat.stat.exists | bool
  block:
    - name: Ensure Infisical frontend systemd service is stopped
      ansible.builtin.service:
        name: "{{ infisical_identifier }}-frontend"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Infisical frontend systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ infisical_identifier }}-frontend.service"
        state: absent

    - name: Ensure Infisical path does not exist
      ansible.builtin.file:
        path: "{{ infisical_base_path }}"
        state: absent
